### ISSUE TITLE
Serve nearup only via HTTPS

### ISSUE THREAD

**Issue by frol** [near/nearup#1]
Let's make it clear that we don't want to downgrade TLS or be redirected (copied from https://rustup.rs/):

```
$ curl --proto '=https' --tlsv1.2 -sSf https://up.nearprotocol.com | python3
```

Using HTTP without encryption and sending it straight to Python interpreter is a way to get some nasty things.

**Comment by ailisp** [comment]
Updated. Thanks!

**Comment by frol** [comment]
@ailisp HTTPS connection times out. Do we need to configure it?

**Comment by ailisp** [comment]
It's now available by `curl --proto '=https' --tlsv1.2 -sSfL https://up.near.dev | python3` (updated readme)
