### ISSUE TITLE
Restaking service

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearup#10]
Want to start the discussion about need to run restaking service.
It has two functions:
 - Restake if node is below online threshold
 - Perform `ping` for staking contracts.

We have the binary available - `cargo build -p restaked` in the nearcore repo.

The caveat is that this service needs to have access to full access key (or user must have contract deployed on their account that allows to issue `StakeAction` from a function call access key).

Thoughts @ailisp @bowenwang1996 @jimmy3dita how we should approach this?

**Comment by stefanopepe** [comment]
To be sure I understood correctly:
- we have a smart contract that works as a watchdog, using the `ping` to understand if the current proposal is sufficient
- if the condition fails, and the stake is not sufficient, we have a `StakeAction` to top-up the balance of the staking contract

What we want to discuss is how `StakeAction` works, e.g.:
1. pulls tokens from the user account automatically, via access key
2. pulls tokens from a liquid smart contract, which could work as a separate account
where 2 implies that users "purchase" the restaking contract storing some additional tokens into it

**Comment by bowenwang1996** [comment]
Smart contract cannot act as a watchdog. We need a separate service (already implemented) to watch the account and also send ping periodically (once an epoch).
