### ISSUE TITLE
Remove the key-generator code from nearup

### ISSUE THREAD

**Issue by chefsale** [near/nearup#103]
Currently this feature is implemented in neard and this can be replaced by neard init.
https://github.com/near/nearup/blob/nearup_v2/nearuplib/util.py#L91

**Comment by chefsale** [comment]
This issue is related: https://github.com/near/nearup/issues/68

**Comment by nickmonad** [comment]
@chefsale It seems that we don't push `neard` to the S3 bucket. Will use `near` until that is resolved. See https://s3.console.aws.amazon.com/s3/buckets/build.nearprotocol.com/nearcore/Linux/1.15.0/8da7b53f1b0c5d10619648b6cfc2b9fd78602278/?region=us-west-1&tab=overview
