### ISSUE TITLE
pulling docker image from the docker hub fails

### ISSUE THREAD

**Issue by vistrcm** [near/nearup#105]
Hello,

I found a small inaccuracy in README.md in the branch nearup_v2.

[According to README.md](https://github.com/near/nearup/blob/cbad05df88ba40c8be08c1b9376b6ae4626f00b3/README.md#pull-the-docker-image), one can pull docker image by 
```
docker pull nearprotocol/nearup
```

By default, docker uses the tag `latest` if the tag is not defined explicitly. Unfortunately, there is not `nearprotocol/nearup:latest` in docker hub: https://hub.docker.com/r/nearprotocol/nearup/tags. Only versioned images like `nearprotocol/nearup:0.5.2`.

So user gest an error like:
```
$ docker pull nearprotocol/nearup
Using default tag: latest
Error response from daemon: manifest for nearprotocol/nearup:latest not found: manifest unknown: manifest unknown
```

Specific versions works fine:
```
$ docker pull nearprotocol/nearup:0.5.2
0.5.2: Pulling from nearprotocol/nearup
d7c3167c320d: Pull complete
131f805ec7fd: Pull complete
322ed380e680: Pull complete
6ac240b13098: Pull complete
efca1e87a64d: Pull complete
2e59e7d9e84e: Pull complete
615bd8fc4418: Pull complete
Digest: sha256:29b62864af94af9de0b8388355e64ef3d83987eebaaad5db18173f89ebcd08ab
Status: Downloaded newer image for nearprotocol/nearup:0.5.2
docker.io/nearprotocol/nearup:0.5.2
```

Not sure what is the correct fix for that: add tag `latest` on docker hub or update README.md.

I can create a PR to update README.md if you think this is the right solution.

**Comment by nickmonad** [comment]
This has been resolved. `latest` now pulls `0.5.2` - We have a ticket to automate this in CI https://github.com/near/nearup/issues/107

**Comment by vistrcm** [comment]
thank you
