### ISSUE TITLE
nearup watcher complains about `net`

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/nearup#109]
Watcher complains about `net`
```
Traceback (most recent call last):
  File "/root/.local/bin/watcher", line 51, in run
    restart_nearup(net)
NameError: name 'net' is not defined
```

This is for `nearup` version `0.5.2` for `betanet` on Ubuntu

**Comment by chefsale** [comment]
It's resolved in 0.5.3. Thanks for the report.

**Comment by chefsale** [comment]
@evgenykuzyakov can you just let me know where did you get this error message? Was it in the watcherogs or somewhere else?

**Comment by evgenykuzyakov** [comment]
It was thrown in `nearup logs --follow`

**Comment by chefsale** [comment]
Thanks.
