### ISSUE TITLE
When will nearup support mainnet?

### ISSUE THREAD

**Issue by lcgogo** [near/nearup#114]
Seems nearup does not support mainnet yet.

`2020-09-24 04:34:22.604 INFO nearup - run: Home directory is /root/.near/mainnet...
2020-09-24 04:34:22.604 ERROR nearup - run: Sorry mainnet is now internal nodes only!!!
2020-09-24 04:34:22.604 ERROR nearup - run: Please use https://rpc.mainnet.near.org to reach mainnet rpc`

**Comment by chefsale** [comment]
We don't plan to support mainnet. We have to remove the mainnet from the run command for now.

**Comment by lcgogo** [comment]
Why? The https://github.com/nearprotocol/nearcore suggested Join the network is using nearup. And the github does not list how to start the mainnet node.

**Comment by chefsale** [comment]
@bowenwang1996 can we add reasoning about not supporting mainnet to the README to explain this a bit better?

**Comment by ilblackdragon** [comment]
I think we should support MainNet network. It should be clear that validators should not be using this though.

**Comment by chefsale** [comment]
@lcgogo so we decided that we will add mainnet support for RPC and bootnodes only, but validators shouldn't be using it. Is that what you were referring to?

**Comment by chefsale** [comment]
I have added mainnet support, while this is only encouraged for RPC/boot nodes and not validators. I'm closing this issue and with the next release: `nearup run mainnet` should be available for use.
