### ISSUE TITLE
Nearup 0.6.0 Stop/Start Botched

### ISSUE THREAD

**Issue by gaia** [near/nearup#122]
i was running the previous version of nearup. logged in to upgrade.

realized that near had crashed. tried to restart, got the alert to remove the lock file.

as soon as the lock file was removed, the watcher starts near with --verbose.

I then start near via `nearup run testnet` and it keeps crashing. possibly because there are 2 processes started, one by me, one by the watcher.

issuing a stop only removes one of the processes (and the wrong one)
![image](https://user-images.githubusercontent.com/87547/94594977-05e4ad80-023f-11eb-9e8c-c114de499b48.png)

if I `kill -9` both PIDs, the watcher starts again another process. see how the error gets output to stdout (letting me know the watcher kicked in)

![image](https://user-images.githubusercontent.com/87547/94595198-578d3800-023f-11eb-90f3-d396739953fc.png)

**Comment by chefsale** [comment]
We are working on getting this resolved.

**Comment by chefsale** [comment]
Thank you for reporting this. cc:@ngmiller

**Comment by chefsale** [comment]
@gaia you shouldn't be running two processes at the same time, as this causes issues. There should be only one neard process running at any time. If the neard dies please kill the watcher

**Comment by gaia** [comment]
> @gaia you shouldn't be running two processes at the same time, as this causes issues. There should be only one neard process running at any time. If the neard dies please kill the watcher

yep no kidding :)

but the only way to run a single process was to reboot the machine.

**Comment by chefsale** [comment]
@gaia can you upload the logs somewhere for me from both ~/.nearup/logs/<network>.log and ~/.nearup/logs/watcher.log?

**Comment by gaia** [comment]
Sent via PM. thanks!

**Comment by chefsale** [comment]
@gaia this has been resolved in the new release, closing this issue and thank you for reporting.
