### ISSUE TITLE
log rotation, as restart truncates logs

### ISSUE THREAD

**Issue by kucharskim** [near/nearup#124]
Logs in `~/.nearup/logs/` are truncated on restart, there is no way to investigate logs from before after restart.

Today (Sep 29, 2020) there was widespread issue in testnet and after restarting I didn't have access to old logs to properly investigate the issue.

Classic way of logfile, logfile.0, logfile.1, logfile.2, ... would be sufficient here.

**Comment by chefsale** [comment]
Thanks we added the log to be append, so the logs should still be around. But yes, will implement the logs to be added to seperate files.

**Comment by kucharskim** [comment]
I think, if you do implement log rotation, and nearup is only running on Linux (tail implementation from coreutils), I guess `tail -f` would need to be changed to `tail -F` in case file descriptor changes, of followed file, after log rotation.

**Comment by chefsale** [comment]
Implemented this, should be released in the next nearup release.
