### ISSUE TITLE
nearup --version or just nearup version support

### ISSUE THREAD

**Issue by kucharskim** [near/nearup#126]
When doing bug reporting it would be nice to quickly know from within the tool, which version it is. You could also add this version information as first line in the log, before neard starts doing it's output (in `~/.nearup/logs/<network>.log`)

```
nearup --version
nearup version
```

or both.

**Comment by chefsale** [comment]
we suppotr `nearup version` from 0.6.0 version, so upgrade to that version

**Comment by kucharskim** [comment]
Yes, indeed. I had old version around of nearup. Now `nearup version` works, after upgrade.
