### ISSUE TITLE
Randomize nearup restarts, so the whole network doesn't go down at the same time

### ISSUE THREAD

**Issue by chefsale** [near/nearup#134]

**Comment by nickmonad** [comment]
Do you mean in the context of testnet and betanet on GCP? Should it be random or just one-by-one?

**Comment by chefsale** [comment]
Ideally we should have some way of doing phase rollouts aka 10percent by 10 percent, to get there that's gonna be a bit tricky and we have to figure out what would be the best way to do so, as a lot of external people are running nearup and maybe there are some limitations on what we can do.

What can we do for now as a dirty hack is once the watcher decides to restart it generates a random number from 1 - 15 or something and thats the amount of minutes it waits to restart, in that way not all the nodes would go down at same time and would give us a uniform distribution of nodes going down in the period of 1 minutes.
