### ISSUE TITLE
Resolve ~ into home folder

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearup#14]
Currently `nearup ... --home=~/test` will actually create a local folder "~" and store data in it.
We might want to do this in the nearcore as well.

**Comment by frol** [comment]
Well, `~` expansion is a shell feature. If you run the command with a space instead of `=` between `--home` and `~/test` you will get the right path:

```
$ nearup ... --home ~/test  # OK

$ nearup ... --home=~/test  # not OK
```

I could not find an example of an existing tool to see what is considered to be a norm here.

**Comment by ailisp** [comment]
I agree with frol here, but if you know any popular cli tool implement arg=~/path expansion I can make that too
