### ISSUE TITLE
Nearup downloads binaries on every run.

### ISSUE THREAD

**Issue by q9f** [near/nearup#149]
Nearup downloads binaries on every run.

Instead, it should check for existing binaries either in $PATH or in `~/.nearup`

**Comment by q9f** [comment]
I see there is a version string stored right next to the binary. Just check that?

`404bc6bf6349803ac10c55f5a51eae7ac3895310`

**Comment by chefsale** [comment]
Yes, we have an issue for that and it should be resolved soon. Thanks for the feedback.

**Comment by chefsale** [comment]
Solved
