### ISSUE TITLE
WARN client: Banning node for sending invalid block headers

### ISSUE THREAD

**Issue by zhiquan911** [near/nearup#157]
Nov 02 12:43:16.136  WARN client: Banning node for sending invalid block headers
Nov 02 12:43:16.136  WARN network: Banning peer Some(ed25519:4NBder5wrEZaaeUA3ZqtF3QiEqMzSV3oXjY6m2bqfbSt@35.196.128.159:24567) for BadBlockHeader
Nov 02 12:43:16.136  WARN network: Banning peer ed25519:4NBder5wrEZaaeUA3ZqtF3QiEqMzSV3oXjY6m2bqfbSt for BadBlockHeader
Nov 02 12:43:16.145  WARN client: Sync: no peers available, disabling sync
-------------------------

I can not sync blocks.

**Comment by bowenwang1996** [comment]
which network is this? Which version of nearup are you running?

**Comment by zhiquan911** [comment]
I follow the docker's command to run `mainnet` network like this:
`docker run -v $HOME/.near:/root/.near --name nearup nearprotocol/nearup run mainnet`

The nearup version is 0.6.4.
The near: Version: 1.13.1, Build: 1384bcde, Latest Protocol: 35

**Comment by bowenwang1996** [comment]
1.13.1 will not work. Please use 1.13.3.

**Comment by zhiquan911** [comment]
> 1.13.1 will not work. Please use 1.13.3.

I use this project's Dockerfile to build. How do I upgrade the near to 1.13.3?

**Comment by bowenwang1996** [comment]
> I use this project's Dockerfile to build. How do I upgrade the near to 1.13.3?

Use https://github.com/near/nearcore/releases/tag/1.13.3

**Comment by zhiquan911** [comment]
> Use https://github.com/near/nearcore/releases/tag/1.13.3

The recommended installation way of nearcore is to use nearup. But nearup installs version 1.13.1 by default. How do I use nearup to install 1.13.3?

**Comment by bowenwang1996** [comment]
> The recommended installation way of nearcore is to use nearup. But nearup installs version 1.13.1 by default. How do I use nearup to install 1.13.3?

1. I don't think the recommended way is to use nearup.
2. nearup should pull the latest release. @chefsale can you verify?

**Comment by chefsale** [comment]
It seems once we have release 1.13.3 we haven't updated the nearup mainnet deployment to the newest version. The mainnet nearup nodes should autoupdate the that version now. If not just manually restart it. Let me know if this is fixed now.

**Comment by zhiquan911** [comment]
> It seems once we have release 1.13.3 we haven't updated the nearup mainnet deployment to the newest version. The mainnet nearup nodes should autoupdate the that version now. If not just manually restart it. Let me know if this is fixed now.

Great! I restart the nearup, the node has autoupdated to newest version.
(near: Version: 1.13.3, Build: 48e00754, Latest Protocol: 36)
However, the node log outputs such an error message:

```log

Nov 06 07:25:19.623 ERROR client: Error processing sync blocks: Invalid Next BP Hash
 Cause: Unknown
Nov 06 07:25:19.623  WARN client: Banning node for sending invalid block headers
Nov 06 07:25:19.623  WARN network: Banning peer Some(ed25519:UeH6Q1wm6ENxH5LBCL8ghiEeXZS5q8ZtbyLPeMR5Mzm@3.250.156.237:24567) for BadBlockHeader
Nov 06 07:25:19.623  WARN network: Banning peer ed25519:UeH6Q1wm6ENxH5LBCL8ghiEeXZS5q8ZtbyLPeMR5Mzm for BadBlockHeader
Nov 06 07:25:22.791  INFO stats: # 9820210 Downloading headers 84%   2/2/40 peers ⬇ 8.3kiB/s ⬆ 0.5kiB/s 0.00 bps 0 gas/s CPU: 1%, Mem: 96.1 MiB
Nov 06 07:25:29.249 ERROR client: Error processing sync blocks: Invalid Next BP Hash
 Cause: Unknown
Nov 06 07:25:29.249  WARN client: Banning node for sending invalid block headers
Nov 06 07:25:29.249  WARN network: Banning peer Some(ed25519:5s3TRM2mhGBnGtYeGss4zGTtpRbdz9fbEdAftrgkHG1F@46.101.211.182:24567) for BadBlockHeader
Nov 06 07:25:29.249  WARN network: Banning peer ed25519:5s3TRM2mhGBnGtYeGss4zGTtpRbdz9fbEdAftrgkHG1F for BadBlockHeader
Nov 06 07:25:32.793  INFO stats: # 9820210 Downloading headers 84%   1/1/40 peers ⬇ 4.1kiB/s ⬆ 0.2kiB/s 0.00 bps 0 gas/s CPU: 1%, Mem: 96.2 MiB
Nov 06 07:25:37.810 ERROR client: Error processing sync blocks: Invalid Next BP Hash
 Cause: Unknown
Nov 06 07:25:37.810  WARN client: Banning node for sending invalid block headers
Nov 06 07:25:37.810  WARN network: Banning peer Some(ed25519:5pRiNCHbXFALoVqHJtqvUdJadT85r6L3GVSnyUeS3GJX@101.36.110.113:24567) for BadBlockHeader
Nov 06 07:25:37.810  WARN network: Banning peer ed25519:5pRiNCHbXFALoVqHJtqvUdJadT85r6L3GVSnyUeS3GJX for BadBlockHeader
Nov 06 07:25:37.828  WARN client: Sync: no peers available, disabling sync
Nov 06 07:25:42.795 ERROR client: Unwrap error: DB Not Found Error: EPnLgE7iEq9s7yTkos96M3cWymH5avBAPm3qx3NXqR8H

```

**Comment by bowenwang1996** [comment]
yeah your database is already corrupted because you were running the old version. You need to wipe out the data folder and resync.

**Comment by zhiquan911** [comment]
Thank you very much! The full node has synced the latest block.
