### ISSUE TITLE
Telemetry URL should be adjusted to set correctly for the relevant network

### ISSUE THREAD

**Issue by frol** [near/nearup#16]
Telemetry should go to the relevant domain for each of the network:

* devnet: https://explorer.devnet.nearprotocol.com/api/nodes
* betanet: https://explorer.betanet.nearprotocol.com/api/nodes
* testnet: https://explorer.nearprotocol.com/api/nodes

*There used to be this problem before with Stake Wars: https://github.com/nearprotocol/nearcore/issues/1788*

*This issue is a follow up of https://github.com/nearprotocol/nearcore/issues/2306*

**Comment by ailisp** [comment]
Config update is done. just need to wait your fix on openssl_probe deployed

**Comment by frol** [comment]
Is the initial config generation fixed?

**Comment by ailisp** [comment]
Yes

**Comment by ailisp** [comment]
Seems fixed in latest devnet deploy. There's a betanet deploy tomorrow, will ensure that works too
