### ISSUE TITLE
Following installation readme didn't work

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearup#162]
# Steps to reproduce

1. pip3 install --user nearup
2. observe ~/.local/bin non existent

# Details

* Mac Os 10.15.6
* fish
* pip 18.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

**Comment by ailisp** [comment]
On Mac pip3 install --user doesn't install to ~/.local/bin, but instead `/Users/<you>/Library/Python/3.7/bin/`, doc probably need an update. @chefsale

**Comment by chefsale** [comment]
The mac builds on nearcore were broken for a while, so we removed the support for Mac and only provided docker support.

In the meantime I have fixed the builds and now added nightly builds for betanet on Mac, also I have created a PR to add back support and testing for Mac, as well updated the docs in: https://github.com/near/nearup/pull/165.
