### ISSUE TITLE
nearup can't be used to run archival mainnet

### ISSUE THREAD

**Issue by puntium** [near/nearup#175]
Currently neard takes an --archive argument with it's "run" subcommand, but there is not way to have nearup launch neard with this argument.

This is with nearup 0.9.0, installed through pip on an ubuntu 20.04 instance.

**Comment by bowenwang1996** [comment]
For now you can manually change `archive` in `config.json` to be `true`.

**Comment by puntium** [comment]
Yup @chefsale helped me through the setup on Discord, so I have something working. File the issue for y'all to track.

**Comment by chefsale** [comment]
This has been resolved in https://github.com/near/nearup/commit/c2f8eec6a9b6aeb083e654684027aea88867b239
