### ISSUE TITLE
The node is out of synchronization and an error is reported

### ISSUE THREAD

**Issue by mayong82** [near/nearup#195]
The error message is as follows:
Jan 24 07:23:17.213 ERROR client: Unwrap error: DB Not Found Error: G1qqaNkdDbTcNKpqVXYt6ZcpZdmu7mYv7NcPU47eoBSs 
 Cause: Unknown    
Jan 24 07:23:27.214 ERROR client: Unwrap error: DB Not Found Error: G1qqaNkdDbTcNKpqVXYt6ZcpZdmu7mYv7NcPU47eoBSs 
 Cause: Unknown    
Jan 24 07:23:37.215 ERROR client: Unwrap error: DB Not Found Error: G1qqaNkdDbTcNKpqVXYt6ZcpZdmu7mYv7NcPU47eoBSs 
 Cause: Unknown    

After restarting the node, this situation will occur again after a period of time
The height of node synchronization is always 57934160
Who has encountered this problem and how to solve it

**Comment by bowenwang1996** [comment]
This is possible if you changes tracking_shard in your config from tracking no shard to tracking some shard and then restarts your node immediately. The node does not have any state for so it cannot process blocks.
