### ISSUE TITLE
The node cannot be synchronized normally after startup

### ISSUE THREAD

**Issue by mayong82** [near/nearup#196]
DEBUG sync: Sync: transition to State Sync.    
Jan 24 08:10:38.383 DEBUG network: Trying to connect to ed25519:Fuf9hVnjACPG4S3CuLcPSCjNM7vApRiS1hpWQfUgaVV9@221.223.24.163:24567
Jan 24 08:10:39.385  INFO network: Error connecting to 221.223.24.163:24567: deadline has elapsed
Jan 24 08:11:38.387 DEBUG network: Trying to connect to ed25519:6gaSUJ5rkV5kqezQYsKST8hQSBuaB2bQ5Evtek6ShcWX@35.212.47.191:24567
Jan 24 08:11:39.388  INFO network: Error connecting to 35.212.47.191:24567: deadline has elapsed
Jan 24 08:12:38.390 DEBUG network: Trying to connect to ed25519:CjNSPfJFmiQRzfYrnrbcusZ235sxx2AgumJAwJXHaZ3f@34.74.120.99:24567
Jan 24 08:12:38.586  INFO network: Error connecting to 34.74.120.99:24567: Connection refused (os error 111)
Jan 24 08:13:38.394 DEBUG network: Trying to connect to ed25519:4M1FXAMHJGx8YmBUTfs3hvCBLpKg7h2hSpv9DduW2KwF@184.92.148.120:24567
Jan 24 08:13:39.395  INFO network: Error connecting to 184.92.148.120:24567: deadline has elapsed
Jan 24 08:14:38.397 DEBUG network: Trying to connect to ed25519:5EmQMwPTUhbkdGdqsUAqg8CoS4WXk9F2z8c4swUZrZeW@34.127.92.207:24567
Jan 24 08:14:39.398  INFO network: Error connecting to 34.127.92.207:24567: deadline has elapsed
Jan 24 08:15:38.399 DEBUG network: Trying to connect to ed25519:7uz4EYUWHBgdouG3mZ5GEcKh7cFaTn45HRPXJ2XWrCra@103.164.54.185:24567
Jan 24 08:15:38.436 DEBUG network: Connecting to ed25519:7uz4EYUWHBgdouG3mZ5GEcKh7cFaTn45HRPXJ2XWrCra@103.164.54.185:24567
Jan 24 08:15:38.437 DEBUG network: ed25519:BZheTRPwkKoJMBSPD3avKVH5pBctj8698L57YWpT9bUr: Peer 103.164.54.185:24567 Outbound started
Jan 24 08:16:38.403 DEBUG network: Trying to connect to ed25519:91SLi6reiaLmCop9fWKL3Wn99AVUEJk5enPSG4fixX3h@35.201.166.215:24567
Jan 24 08:16:39.403  INFO network: Error connecting to 35.201.166.215:24567: deadline has elapsed
Jan 24 08:17:38.405 DEBUG network: Trying to connect to ed25519:2a5NSZfeDkKijsq3mefL1gDrJwJ38vGiYuiNwgJcmrvd@38.77.226.140:24567
Jan 24 08:17:38.558  INFO network: Error connecting to 38.77.226.140:24567: Connection refused (os error 111)
Jan 24 08:18:38.409 DEBUG network: Trying to connect to ed25519:4Leu81M3prD7QDd4vCuQRU7VfUVXh7hFaVs4y36LWef4@35.187.126.200:24567
Jan 24 08:18:39.409  INFO network: Error connecting to 35.187.126.200:24567: deadline has elapsed
Jan 24 08:19:38.411 DEBUG network: Trying to connect to ed25519:GaXCiLFfdz5V3dyqMgJzbkRCrLbeiTcU8GY3PDE111BZ@35.236.133.117:24567
Jan 24 08:19:39.412  INFO network: Error connecting to 35.236.133.117:24567: deadline has elapsed
Jan 24 08:20:38.414 DEBUG network: Trying to connect to ed25519:8pfoP3ZBodaMjT5KwDM6basF6xkH4chudAhoxTzqMJJC@34.81.165.152:24567
Jan 24 08:20:39.414  INFO network: Error connecting to 34.81.165.152:24567: deadline has elapsed
Jan 24 08:21:38.416 DEBUG network: Trying to connect to ed25519:336UDLgGeDbVWyX8utxCnqqk4WDXn5aKsWvcm6z2qY3v@34.75.125.234:24567
Jan 24 08:21:38.612  INFO network: Error connecting to 34.75.125.234:24567: Connection refused (os error 111)
Jan 24 08:22:38.418 DEBUG network: Trying to connect to ed25519:Foe3TZcPQx5PP7Vkd1deWn41Ht8zM7pLGFYfYKY8iq6a@35.204.215.120:24567
Jan 24 08:22:39.420  INFO network: Error connecting to 35.204.215.120:24567: deadline has elapsed
Jan 24 08:23:38.420 DEBUG network: Trying to connect to ed25519:4Mo9p5gi29h3nVieNS94p4vFrYNPWRomrYZm3YvFJ2Bc@18.163.249.168:24567
Jan 24 08:23:39.422  INFO network: Error connecting to 18.163.249.168:24567: deadline has elapsed
Jan 24 08:24:38.423 DEBUG network: Trying to connect to ed25519:7azjQA7wXnz5wLaKeLCxgfkmNyuCAMhxfZFjt8UkvdT4@95.216.96.36:24567
Jan 24 08:24:38.748 DEBUG network: Connecting to ed25519:7azjQA7wXnz5wLaKeLCxgfkmNyuCAMhxfZFjt8UkvdT4@95.216.96.36:24567
Jan 24 08:24:38.749 DEBUG network: ed25519:BZheTRPwkKoJMBSPD3avKVH5pBctj8698L57YWpT9bUr: Peer 95.216.96.36:24567 Outbound started
Jan 24 08:25:38.425 DEBUG network: Trying to connect to ed25519:FaUBsssYoGgjRFVeKpgXSaUVBuytn1ssExodCoXmxoHG@65.108.42.131:24567
Jan 24 08:25:38.748  INFO network: Error connecting to 65.108.42.131:24567: Connection refused (os error 111)
Jan 24 08:26:38.427 DEBUG network: Trying to connect to ed25519:BJSe929GyStMMu9QX9Shamzm15KxwTqf9uGwaXsVxE6Z@35.204.140.0:24567
Jan 24 08:26:39.429  INFO network: Error connecting to 35.204.140.0:24567: deadline has elapsed
Jan 24 08:27:38.429 DEBUG network: Trying to connect to ed25519:6RV38BGyY8Lt8BAcJD3hpKMYghnfxPmniMxXFNgHaRd3@35.221.173.157:24567
Jan 24 08:27:38.444 DEBUG network: Connecting to ed25519:6RV38BGyY8Lt8BAcJD3hpKMYghnfxPmniMxXFNgHaRd3@35.221.173.157:24567
Jan 24 08:27:38.445 DEBUG network: ed25519:BZheTRPwkKoJMBSPD3avKVH5pBctj8698L57YWpT9bUr: Peer 35.221.173.157:24567 Outbound started
Jan 24 08:28:38.431 DEBUG network: Trying to connect to ed25519:9zPEHXmRsppHvmRHmXonefJCzpUXciMSVeCVJxvYRQyW@35.202.228.127:24567
Jan 24 08:28:39.432  INFO network: Error connecting to 35.202.228.127:24567: deadline has elapsed

**Comment by bowenwang1996** [comment]
Please provide more detailed information. For example, which version of neard you are running and which network this is. Also it is not clear what happens afterwards. Did the node just get stuck?
