### ISSUE TITLE
Second nearup execution breaks since no tracking branch is set

### ISSUE THREAD

**Issue by frol** [near/nearup#2]
https://github.com/nearprotocol/nearup/blob/a086ea9df891d680f5f35f1dcca6805237fee20b/nearup#L17-L18

It seems that this should fail since `git pull` without specifying a branch will not succeed unless some branch is set to be an upstream.

**Comment by ailisp** [comment]
I cleared ~/.nearup and ~/.near, try the first install. Then push a new commit to nearup. Then nearup again. Seems it work for me (there isn't error, also `git log` correctly in ~/.nearup), what is the git version you have that doesn't work?

**Comment by frol** [comment]
Seems to be not an issue after all, but I don't understand why. Anyway, closing...
