### ISSUE TITLE
Update delay - Allow nodes to configure a delay in getting new releases

### ISSUE THREAD

**Issue by TrevorJTClarke** [near/nearup#203]
For nearup on testnet/guildnet - when a new version is released, all nodes running nearup get the update immediately when they detect it. This causes a significant amount of the network to restart and sync/migrate. A couple cases on guildnet have shown that it was enough to fully stall the network. 

Idea here:
- create a config that allows a node to stall its adoption of every new release
- set a random timer, so there is less node-adoption collision

**Comment by bowenwang1996** [comment]
> create a config that allows a node to stall its adoption of every new release

This is done in https://github.com/near/nearcore/pull/6309

> set a random timer, so there is less node-adoption collision

It feels like this should be done in nearup rather than neard itself

**Comment by TrevorJTClarke** [comment]
> It feels like this should be done in nearup rather than neard itself

Yes, thats why this issue is in nearup ;)
