### ISSUE TITLE
Add testing to cover critical paths

### ISSUE THREAD

**Issue by ailisp** [near/nearup#21]
As nearup become not trivial, it's nice to have some test to ensure new changes doesn't break. And as nearup always update master branch, we need to ensure master branch always work. (nearup doesn't seem to be complex to have beta or stable branch now)

**Comment by nickmonad** [comment]
@chefsale Can you elaborate on some coverage areas we may be missing here?

**Comment by nickmonad** [comment]
* watcher tests (arguments, etc)
* in localnet, not running the watcher
