### ISSUE TITLE
Self-update command is needed

### ISSUE THREAD

**Issue by frol** [near/nearup#3]
Example:

```
$ rustup self update
```

Currently, the implementation can be as simple as `cd ~/.nearup && git pull origin master`.

**Comment by ailisp** [comment]
Currently nearup always self update at start. It seems doesn't slow much but more convenient to user . Rustup can't be this luxury because it's 12M :)

**Comment by frol** [comment]
I see. This should be documented.

> Rustup can't be this luxury because it's 12M

Well, it is also risky to try updating on every execution. I mean, every software has bugs, and you can introduce new ones and auto-update to those across the community can be heart-breaking

**Comment by ailisp** [comment]
documented now
