### ISSUE TITLE
Add Support for mainnet

### ISSUE THREAD

**Issue by damons** [near/nearup#39]
Should `nearup` also provide an option to start a node for `mainnet` ?

**Comment by ailisp** [comment]
Currently there's no way to join mainnet (because of our firewall rules) so nearup doesn't provide mainnet. I can add a stub to give people message: `Sorry mainnet is now internal nodes only, please use https://rpc.mainnet.nearprotocol.com to reach mainnet rpc`

**Comment by ailisp** [comment]
added a stub mainnet. Will come back once mainnet accepts to join
