### ISSUE TITLE
nearup devnet does not create correct account

### ISSUE THREAD

**Issue by maxzaver** [near/nearup#40]
# Steps to reproduce

```bash
nearup devnet
```

When presented with the prompt: `Enter your account ID (leave empty if not going to be a validator):` enter `ethrelay`.

After the node starts check the state of the `ethrelay`:
```bash
http post http://localhost:3030 jsonrpc=2.0 id=dontcare method=query \ 
  params:='{
    "request_type": "view_account",
    "finality": "final",
    "account_id": "ethrelay"
  }'
```
The output:
```json
{
    "error": {
        "code": -32000,
        "data": "account ethrelay does not exist while viewing",
        "message": "Server error"
    },
    "id": "dontcare",
    "jsonrpc": "2.0"
}
```

Check the genesis config of the node:
```bash
docker exec -ti nearcore bash
cat /srv/near/genesis.json | grep ethrelay
```
Observe that genesis records do not contain `ethrelay`. Then do:
```bash
cat /srv/near/validator_key.json
```
Observe that it refers to `ethrelay` account:
```json
{
  "account_id": "ethrelay",
  "public_key": "ed25519:GEcrZQEsSL73hAUrzuetURygVLgosRZvz2VQfskvLTqd",
  "secret_key": "ed25519:39h9N1whsarAtpcJpgEPYQ1MX6azAjRSxkTmZCYAErmwkbdX2CqLh8QkfLshtvyW39RX5NrE983jXSYqcMqpMmCP"
}
```

## Expected behavior
`ethrelay` account is created in the system through the genesis records.

**Comment by ailisp** [comment]
This isn't a bug. Devnet genesis is already created at the time of deployment, so it's not possible to add user's account when you do nearup (which download devnet genesis, etc. and start a node locally that join devnet). So you have to create account with devnet wallet, and stake with near-shell (similar to how you would join betanet and testnet)

**Comment by bowenwang1996** [comment]
> ethrelay account is created in the system through the genesis records.

Why is this the expected behavior? Devnet is not a local network

**Comment by maxzaver** [comment]
I see.
