### ISSUE TITLE
Hardcoded home paths need to be removed

### ISSUE THREAD

**Issue by maxzaver** [near/nearup#43]
nearup allows specifying home folder using `--home` flag but it still has some hardcoded paths e.g. https://github.com/near/nearup/blob/master/nearuplib/localnet.py#L38 Which makes `--home` flag not usable.

**Comment by ailisp** [comment]
This isn't the home path but where nearup would store logs. I think this path is as expected and doesn't prevent run a node with user provided home path

**Comment by maxzaver** [comment]
AFAIU `--home` describes the location where nearup stores its data, like pid, and potentially the source. I am not sure what would be the reason to have a different directory for logs. Besides, if I am using nearup from source (without installing it system-wide) then `~/.nearup` directory will not  exist and logs writing will fail.

**Comment by ailisp** [comment]
Makes sense but there's pros and cons to put systemwide ~/.nearup (major pros: easy for most nearup users who want to join testnet as simple as possible. and stop, view logs should "just work". put log file and node pid file in --home makes this not possible to simply `nearup stop` and `nearup logs`, major cons: not friendly for advanced user and not flexible for localnet, run multiple localnet collect logs separately)

The design tradeoff is to satisfy non advanced users, so log and pid file is in ~/.nearup, but it may help to add a --log-dir option or make log special in localnet case? wdyt @mfornet 

As for running a local nearup, suggested way is to install nearup first and clone repo, do any changes in the cloned repo, and run python3 main.py <nearup commands> <args>: https://github.com/near/nearup#contributions

**Comment by maxzaver** [comment]
Then I don't understand the usefulness of `--home` argument if it places only some files into `--home` directory. In what case it is going to be useful?


Also, if we are talking about advanced users they should be comfortable with running `nearup stop --home <path>`.

**Comment by ailisp** [comment]
> Then I don't understand the usefulness of --home argument if it places only some files into --home directory. In what case it is going to be useful?

It's compatible to how you run a nearup docker node. log isn't stored in homedir but more like stored in an internal place. For docker it's totally internal. For nodocker treat it as internally maintained by nearup. I think your propose on unify `nearup logs` will also nicely solve this: if people want to see log, nearup logs <node-i> will see it. logs is store internallly, either by nearup or docker. If people want to extract log, they can goes from `nearup logs -f`

Of course, with this treat log as internal approach, we shouldn't no longer tell user to "View logs in ~/.nearup/xxx/log"

**Comment by chefsale** [comment]
I think this issue can be closed, also for the logging issue on localnet we have: https://github.com/near/nearup/issues/55
