### ISSUE TITLE
nearup stop sometimes fails with non-descriptive error

### ISSUE THREAD

**Issue by maxzaver** [near/nearup#44]
Example:
```bash
nearup stop
Traceback (most recent call last):
  File "/Users/maksymzavershynskyi/.nearup/main.py", line 78, in <module>
    stop()
  File "/Users/maksymzavershynskyi/.nearup/nearuplib/nodelib.py", line 408, in stop
    stop_native()
  File "/Users/maksymzavershynskyi/.nearup/nearuplib/nodelib.py", line 425, in stop_native
    str.strip, line.strip(' \n').split("|"))
ValueError: not enough values to unpack (expected 3, got 2)
```
It is not possible to understand what caused the error without code discovery. It is not clear whether this is a bug or a lack of verbosity, so I will assign both labels.

**Comment by damons** [comment]
I get this whenever I use `nearup stop` combined with starting `neard` using the `--nodocker` option.  This may be related to adding `--nodocker` support to `nearup` ?  

https://github.com/near/nearup/issues/41

**Comment by ailisp** [comment]
@nearmax what's your:
```
➜  ~ cat ~/.nearup/node.pid 
6945 | /home/bo/.nearup/near/devnet/near --home /home/bo/.near/devnet run | devnet
```
?

**Comment by ailisp** [comment]
@damons You got this error too I guess this is mac only issue, it might generate a different node.pid file on mac. @mfornet and me tested this we're both testing on linux :thinking:

**Comment by maxzaver** [comment]
> @nearmax what's your:
> 
> ```
> ➜  ~ cat ~/.nearup/node.pid 
> 6945 | /home/bo/.nearup/near/devnet/near --home /home/bo/.near/devnet run | devnet
> ```
> 
> ?

2638 | /Users/maksymzavershynskyi/Projects/nearcore/target/debug/neard --home /Users/maksymzavershynskyi/.rainbowup/near/node0 run

**Comment by ailisp** [comment]
The new format of node.pid is introduced in https://github.com/near/nearup/commit/171f2cef34034a3226c6f1e2a1fe7a8fdf29d908#diff-c6ed1ed57915bbe1aa21913b295946cdR317

I suspect your nearup failed to auto update. Can you see git rev-parse HEAD in ~/.nearup?

**Comment by maxzaver** [comment]
6124424a803aa3a7cb0acb9cceb0424764187794

**Comment by maxzaver** [comment]
Should we be using PyPi?

**Comment by ailisp** [comment]
That's the latest. I see the problem. the format update only in devnet/betanet/testnet. so localnet's format is still old. I'm pushing the fix, can you try again, delete ~/.nearup/node.pid, nearup localnet and nearup stop. (nearup will auto perform my update)

**Comment by ailisp** [comment]
> Should we be using PyPi?

Do you mean make this as a lib/cli tool in pypi or using any pypi dependencies?

**Comment by ailisp** [comment]
We probably should add ci: #21 for nearup, it's becoming more and more complicated

**Comment by ailisp** [comment]
@damons This error should not affect betanet. It's possible you have node.pid generated by old nearup but when you nearup stop, nearup has upgraded. can you try delete ~/.nearup/node.pid and retry:
```
nearup betanet --nodocker
nearup logs -f
C-c
nearup stop
```
And stop should not give error

**Comment by maxzaver** [comment]
> > Should we be using PyPi?
> 
> Do you mean make this as a lib/cli tool in pypi or using any pypi dependencies?

Make it installable with pypi, just like near-shell is installable from npm. To avoid copying from github.

**Comment by maxzaver** [comment]
I am currently writing rainbowup that uses nearup and there is no good way to install it as a dependency.

**Comment by ailisp** [comment]
👍I see, will do. Near-ops would also benefit if it can import nearup as a
lib
