### ISSUE TITLE
nearup adds path to ~/.profile which does not work on Catalina

### ISSUE THREAD

**Issue by maxzaver** [near/nearup#46]
Adding path to ~/.profile has no effect on Mac Os Catalina. I have to manually add it to ~/.zshrc

**Comment by ailisp** [comment]
One weird thing I look around other tools: rust up and nvm all only add to
.profile, but rustup is then in path, but nvm doesn’t 🤔

**Comment by ailisp** [comment]
I figured out. rustup adds source in ~/.zprofile. Weird thing is zsh load both .profile and .zprofile when it's on linux, but only load .zprofile on mac...

**Comment by ailisp** [comment]
@nearmax Fixed and tested with a mac without nearup. You need to delete `source $HOME/.nearup/env` in .profile and rerun nearup to add it to zprofile. Then just open a new terminal window and nearup is in path

**Comment by ailisp** [comment]
@bowenwang1996 add path to fish now and works on linux. Can you try on your fish? (Delete `source $HOME/.nearup/env` from .profile, and run nearup. Then open a new terminal and nearup should in path)

**Comment by bowenwang1996** [comment]
@ailisp yeah it works for me
