### ISSUE TITLE
Improve validator onboarding process

### ISSUE THREAD

**Issue by ilblackdragon** [near/nearup#59]
Currently when nearup is ran first time, it's completely unclear for people what is going on.

Issues:
 - Unclear what account id to enter
 - People enter invalid account ids
 - People don't know that printed key is the validator key

What we should do:
 - Describe what is going on 
 - Suggest first to create account (and also link to how to deploy staking contract there).
 - When entering validator id - check that it already exists and if not - let user know what they should do to create it (see prev step)
 - Print example `near stake <account_id> <staking_key>` line instead of just validator key.

**Comment by frol** [comment]
IMO, we should make nearup transparent, meaning, clearly state what and how it is going to run, so one can just do the same steps manually if necessary.

**Comment by frol** [comment]
@jimmy3dita brought up another good request: headless deployment, so nearup should have a mode where it does not ask any questions and just deploy a new node.

**Comment by ailisp** [comment]
> @jimmy3dita brought up another good request: headless deployment, so nearup should have a mode where it does not ask any questions and just deploy a new node.

This is implictly supported now, if you provide --account-id. After we "transparently on boarding" we'll also update document. This will be updated too

**Comment by ilblackdragon** [comment]
@bowenwang1996 did we end up modifying what are first steps of the node operator and validator look like using nearup?

**Comment by bowenwang1996** [comment]
I don't think so. Assigning @marcelo-gonzalez to take a look at this
