### ISSUE TITLE
How to create master account for localnet?

### ISSUE THREAD

**Issue by frol** [near/nearup#64]

**Comment by mfornet** [comment]
You can always use the account from validators given that you already have their keys:

```
nearup localnet
export NODE_ENV=local
near create_account my_new_account --masterAccount node0 --initialBalance 1000 --keyPath ~/.near/localnet/node0/validator_key.json
```

**Comment by Mouradif** [comment]
right now this gives the following error:

```
An error occured
Error: Top-level accounts must be at least 32 characters.
Note: this is for advanced usage only. Typical account names are of the form:
app.alice.test, where the masterAccount shares the top-level account (.test).
```

I got it to work by doing this instead: 

```
near create_account my_new_account.node0 --masterAccount node0 --initialBalance 1000 --keyPath ~/.near/localnet/node0/validator_key.json
```

But it seems a bit weird that when I spawn a localnet I have these 4 validator accounts node0...node3 whose addresses are node0...node3. How do I mimic the other networks' behaviour and get account names that end in `.localnet` for example?
