### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by ghost** [near/nearup#65]
Was working for a while. I did a nearup stop and started the service again. Getting this:

```
$ nearup betanet --nodocker
Using officially compiled binary
Downloaded binary version is up to date
Traceback (most recent call last):
  File "/home/stack/.nearup/main.py", line 83, in <module>
    args=sys.argv[1:])
  File "/home/stack/.nearup/nearuplib/nodelib.py", line 512, in setup_and_run
    home_dir, init_flags, no_gas_price)
  File "/home/stack/.nearup/nearuplib/nodelib.py", line 95, in check_and_setup
    open(os.path.join(os.path.join(home_dir, 'genesis.json'))).read())
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 27315 column 17 (char 35842915)
```

**Comment by mfornet** [comment]
It looks for some reason that your `genesis.json` file got corrupted. To verify this is the case compute the md5 file of `genesis.json`:

```
$> md5sum ~/.near/betanet/genesis.json
83baa48f406b565cf3eaf1d7a0090c44  
```

If there is a missmatch in the md5hash you can fix it using one of the solutions below:

Fix 1: Remove `~/.near/betanet` folder and start over. Cons: you will need to download all the state again (which for betanet is small, so it isn't a big problem).

Fix 2: Replace `~/.near/betanet/genesis.json` with latest genesis. Download it from https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/betanet/genesis.json.

**Comment by ghost** [comment]
Thanks. That fixed it.

But why was it corrupted in the first place? Saw it happen to somebody else too.

**Comment by mfornet** [comment]
Not sure how it got corrupted! Maybe nearup was stopped in the middle of the download, but AFAIK once it is downloaded, genesis.json is not longer modified.
