### ISSUE TITLE
Can't regenerate validator_key.json

### ISSUE THREAD

**Issue by nowooj** [near/nearup#68]
Enter the validator account id when starting the node for the first time.

However, if I want to start the node with a different account id, I need to delete all data and get re-sync.

I think I need the function to generate validator_key.json. If you think it's necessary, and if you don't have the time, just choose cmd and I think I can contribute.

**Comment by ailisp** [comment]
Sounds a useful feature to me.
> I think I need the function to generate validator_key.json. If you think it's necessary, and if you don't have the time, just choose cmd and I think I can contribute.

Would be great to see your PR
