### ISSUE TITLE
Cleaning up nearup doc

### ISSUE THREAD

**Issue by ailisp** [near/nearup#70]
nearup log is currently comprehensive due to many people's help, but it's becoming lengthy and not very organized as a single file. I think it's better to make readme as a table of content that fit in one screen, and organize information in `docs/xxx.md`. I'm not good at writing and organize the content so I assigned  more versatile people here :)

**Comment by stefanopepe** [comment]
Happy to discuss the details! At a high level, we have to decide if we want to keep nearup as a key component for validators, or we want them to start their nodes with manual scripts on nearcore, and keep this software only for developers and contributors.

The former is heavier in terms of documentation (which is a con) but raises the bar to become validator - which is a pro!
Is NEAR using internally nearup? Or we use something else?

**Comment by mfornet** [comment]
> Is NEAR using internally nearup? 

I'm using nearup,

 Also nearup is a great entry point for validators, both non professionals which want to test and play with NEAR, and for professional validators to see how our scripts work and start adapting theirs to their needs.

**Comment by ailisp** [comment]
I'm using nearup on dev machines, our remote notes currently doesn't use nearup but it's planned. 
> keep nearup as a key component for validators

I prefer this and it's also for developers/contributors, but for those who want advanced setup that skip nearup, we'll provide nice documentation for them, and I think this documentation fits here, so "nearup" would mean both  a nearup tool and "how to run near up doc"

**Comment by stefanopepe** [comment]
I like the idea of keeping it open, as some validators run their nodes via Kubernetes and they need lower-level docs on how to start nearcore from there.
I think the first step is to have two tutorials linked in the README.md file:
- nearup for developers and contributors
- nearup for validators

I think there is no room for "non-professional" validators at the moment, as the number of seats and the needed stake is very high (millions of $NEAR tokens), and it will be very difficult for small operators to get that much. 
Also, we don't really want users to run the network from their gaming PC at home, as we need server-grade connectivity and availability (e.g., we shouldn't have nodes rebooting to apply the latest Geforce patch or a wi-fi router in the middle).

**Comment by ailisp** [comment]
> I like the idea of keeping it open, as some validators run their nodes via Kubernetes and they need lower-level docs on how to start nearcore from there.

Also, there is a pending related task #22, if it's done, nearup would include that template, so people can quickly just modify at most a few parameters to get near run in k8s

**Comment by chefsale** [comment]
Is there any updates on this one: @ailisp @jimmy3dita @amgando or this is obsolete?

**Comment by chefsale** [comment]
As well linking this issue as it seems possibly related: https://github.com/near/nearup/issues/71

**Comment by mfornet** [comment]
@chefsale Why is this being closed? The current README has documentation about how to run a node in MacOS which probably makes more sense to have in a separate readme. Are we tracking nearup documentation in any other place?

**Comment by chefsale** [comment]
@mfornet all the relevant documentation is now on nearup_v2 branch and pypi as we made a major refactor and are migrating validators by the end of the week. After that the new docs will be merged and the current README will be deprecated. Only support on MacOS will be through docker.
