### ISSUE TITLE
After restarting nearup all old logs are deleted

### ISSUE THREAD

**Issue by k0kk0k** [near/nearup#78]
Auto logs removing is not very useful when you need to view old logs (those was before restarting the node). This is especially actual in the test environment (`testnet`, `betanet`).

**Comment by chefsale** [comment]
Is this related to the nearup and watcher logs only or also neard logs?

**Comment by chefsale** [comment]
This should be fixed in the next release made all the logs appendable and not overriden.

**Comment by k0kk0k** [comment]
> Is this related to the nearup and watcher logs only or also neard logs?

i used nearup logs `nearup logs --follow` only
