### ISSUE TITLE
auto-update is potentially broken

### ISSUE THREAD

**Issue by bowenwang1996** [near/nearup#88]
Validators on testnet report that nearup doesn't automatically update the node when there is a new release. They have to manually stop and restart to update to the new version.

**Comment by chefsale** [comment]
I think we don't update the watcher but only nearup, that's why the nodes needed to be restarted. I think that the restart should be fixing it now. If not the watcher will be needed to be stopped. I will look into this, as well figure out how can we update the watcher also.

**Comment by chefsale** [comment]
Yes, the watcher will be restarted on nearup stop that's why it wasn't pulling. Verified it, so now we just have to figure out a way to update the watcher an not only the nearup code.

**Comment by bowenwang1996** [comment]
Actually the issue seems worse. When we release a new version, nearup will detect that there is now a new version, but because of the issue with update, it will shutdown the node and fail to restart.

**Comment by chefsale** [comment]
This still is possibly an issue and we need to get some kind of grace period before the update so not all the nodes go down at same time as well, still investigating and write a NEP for v2.

**Comment by chefsale** [comment]
Closing this, as we know its not the auto update causing this but the release not having the proper binary. Created two seperate tasks to fix that:
https://github.com/near/nearup/issues/91
https://github.com/nearprotocol/near-ops/issues/105
