### ISSUE TITLE
Automated log report for our public Betanet

### ISSUE THREAD

**Issue by stefanopepe** [near/nearup#9]
We are going to release Nearup internally and soon to the community. This will enable us to do a lot of testing and catch more bugs from the logs.
However, collecting logs from a decentralized network of nodes requires multiple manual and complicated commands, and most of the users have no idea how to do that.
The idea is to automate this logs collection, as follows:
- enable some form of "verbose logging" from the `nearup` start command, to collect additional information (e.g. using the RPC [healthcheck endpoint](https://docs.nearprotocol.com/docs/roles/integrator/faq#does-a-node-expose-an-interface-for-retrieving-health-telemetry-in-a-structured-format-ex-json-over-rpc))
- output this log on a .log file (or append this information to system logs)
- upload the logs automatically on some NEAR logging server, such that authorized devs can look into it whenever needed

As a user, I want to send my logs automatically, such that I can help the team in case of issues
As a developer, I want to collect these logs in a single place, such that it's easier for me to analyze them

**Comment by stefanopepe** [comment]
(from today's conversation with @damons and @bowenwang1996 )

**Comment by ailisp** [comment]
Just want to create the same issue from the idea of @damons's presentation today :)

**Comment by bowenwang1996** [comment]
Actually there are two problems here:
* How much performance will we sacrifice if we turn debug log on?
* Assuming it is acceptable to turn debug log on, we need to only print info level logs to the console but write everything to a log file.

**Comment by stefanopepe** [comment]
Happy to run some benchmark and post here the cpu/memory footprint

**Comment by ailisp** [comment]
How is debug log affect performance? Any one has experiment result

**Comment by bowenwang1996** [comment]
Haven't had the time to run it but I think it doesn't block us from setting up a service to collect logs (even just non debug logs).

**Comment by stefanopepe** [comment]
So far, I've been able to export logs using this command:
```
docker logs nearcore --tail 50000 2>&1 | tee nearcore$(date +"%Y%m%d%H%M").log
```
It will extract the last 50,000 lines of and create a logfile with date and time (doesn't specify the time zone).

It may be cool to have NEAR-authenticated `scp` tool, to automatically send logs - paying $NEAR to avoid Sybil attacks 🤓

**Comment by ailisp** [comment]
> It may be cool to have NEAR-authenticated scp tool, to automatically send logs - paying $NEAR to avoid Sybil attacks nerd_face

I'm also considering have upgrade logs is the real challenge. Also can user trigger a manual log report? Or it's automatic only and happen only at crash (actually crash report). We also need to authenticate them access to our log server (we don't have one) to put the log.
Existing log servers I can found are all server to server log collection (you have control to server to not spam), but for client to server that has essential limit and organize logs, I don't know any

**Comment by stefanopepe** [comment]
By now, the only way to send you the logs is to manually issue the command above, zip the file, and `scp` it somewhere.

If near-shell can issue a pubkey/transaction for this job (e.g. a basic access contract), the log server might keep a local whitelist of authorized pubkeys (retrieved from the block explorer), and allow the authorized nodes to login and `scp` the log file there automatically.
Users are already familiar with the process (they create the stake transaction more or less the same way)

**Comment by ailisp** [comment]
This sounds good but we don't want nearup to depend on near-shell, so maybe the feature should be added on near-shell side.

And we want to make sure when log is collected. My understanding is only when there's a crash or user intend to send us some log because he had some issue. It's not going to be a real time log collection, does this like you're thinking?

**Comment by bowenwang1996** [comment]
@ailisp yes there is no need for real time log collection.

**Comment by ailisp** [comment]
@jimmy3dita I see. I made #30 to collect no docker logs. There's a few tasks left to archive your proposed process
1. made a smart contract deploy on devnet/betanet/testnet provides two methods:
    - authenticate: send a little near, auth the pub key owner to allow upload, valid for 10 minutes
    - check auth: for our server to check you have authenticated to do upload
2. in near-shell add `near auth log`
3. in nearup add `nearup logs upload betanet` to:
    - collect log, pack. besides the neard log we also need some system info, version, etc.
    - call `near auth log`
    - call scp, or maybe simply curl --upload-file with your pubkey as auth token
4. implement near log server:
    - if use scp approach, it's a daemon that would watch for blockchain, update ~/.ssh/authorized_keys as there is new authenticate happened in blockchain (however we don't have subscribe to blockchain event yet, so this need to pull all blocks, or make smart contract's check_auth return all pub keys currently authorized)
    - if use curl --upload-file approach, it's a http server, which you provide pubkey, and this server call check_auth to see if you authorized to upload file, accept the file (this seems simpler to me)

I think each of task might be a suitable hackthon work, 2. and 4. maybe simpler than 1. 3.

**Comment by bowenwang1996** [comment]
@ailisp why do we need a smart contract? I think requiring login with NEAR is sufficient and I don't see the benefit of having a smart contract.

**Comment by ailisp** [comment]
@bowenwang1996 It's necessary because Stefano mentioned want user to sign txn to "pay" to log. And smart contract tracks who paid to log.
If we don't need user to pay we can simply require user send this with actual log:
{ accountid, pubkey, timestamp, signature }
and we check:
- accountid on chain, has given pubkey, timestamp is within 1 minute
- signature is signed by keypair of pubkey of {accountid, pubkey, timestamp}

This seems not need smart contract, and even not need near-shell

**Comment by bowenwang1996** [comment]
> want user to sign txn to "pay" to log

On testnet tokens are free. How does it work?

**Comment by ailisp** [comment]
That's correct :D I suggest they send log with the http headers:  { accountid, pubkey, timestamp, signature } then. And our log server should be a simple http server to do that authentication then accept upload log

**Comment by bowenwang1996** [comment]
@ailisp sounds good to me.

**Comment by stefanopepe** [comment]
+1 to keep it simple and remove any need for smart contracts.

Tokens are free, but limited and resistant to Sybil attacks =)

**Comment by chefsale** [comment]
We now append only the logs for both nearup, neard an the watcher, we collect logs for our nodes, but can't ask validators to upload the logs if the aren't willing to do so. If there is an issue we usually get the logs now through discord from them.
