### ISSUE TITLE
Not showing help on re-installs

### ISSUE THREAD

**Issue by defiboy** [near/nearup#92]
If I run 2 times the command to install nearup:

```
curl --proto '=https' --tlsv1.2 -sSfL https://up.near.dev | python3
```
The second time it will show the nearup help, which is confusing because I cannot know if the Nearup was installed before or not.

What I would expect to see is something as for instance, if I run:

```
brew install minikube
```

The second time I will receive:

Warning: minikube 1.12.2 is already installed, it's just not linked
You can use `brew link minikube` to link this version.

This can also be helpful for automation tools, maybe if I reinstall and nearup is installed show just a warning message and return 0?

**Comment by mfornet** [comment]
@defiboy iirc the command `curl --proto ...` is used by some automated tools that don't assume `nearup` is installed, so it can be used as if it is nearup itself (it passes to `nearup` the arguments after installation).

However I added a special message when `nearup` was already installed in #94 that hopefully works for you.
